version: "3.7"

volumes:
  db-data:
    external: false

services:
  cache:
    image: redis:6.0-rc1

  db:
    image: postgres:9.5
    volumes:
      - db-data:/usr/local/pgsql/data

  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
